"use client";

import { useMemo,useState,type FormEvent,type ReactNode } from "react";
import { createKeywordReviewFamily,createKeywordReviewPackage,decideKeywordReview } from "../../lib/api-client/domestic.js";
import type { Result } from "../../lib/api-client/http.js";
import type { KeywordReviewDecision } from "../../runtime/keywords/contracts.js";
import type { BaiduKeywordReadModel } from "../../runtime/read-models/domestic-workspaces.js";
import { ActionFeedback } from "./ActionFeedback.js";

type ReviewFilter="ALL"|"PENDING"|KeywordReviewDecision;
const reviewText=(value:KeywordReviewDecision|null,packaged:boolean)=>value==="CONFIRMED"?"已确认":value==="CHANGES_REQUESTED"?"需要修改":value==="REJECTED"?"未通过":packaged?"待处理":"待提交审核";

export function BaiduKeywordReviewPanel({projectId,data,onChanged}:{readonly projectId:string;readonly data:BaiduKeywordReadModel;readonly onChanged:()=>void}):ReactNode{
  const [selected,setSelected]=useState<readonly string[]>([]);const [label,setLabel]=useState("");const [rationale,setRationale]=useState("");const [pending,setPending]=useState(false);const [feedback,setFeedback]=useState<Result<unknown>|null>(null);const [filter,setFilter]=useState<ReviewFilter>("ALL");const [notes,setNotes]=useState<Record<string,string>>({});
  const selectedRows=data.keywords.filter(row=>selected.includes(row.normalizedFormId));const selectedSnapshot=selectedRows[0]?.snapshotId;
  const families=useMemo(()=>data.reviewFamilies.filter(item=>filter==="ALL"||(filter==="PENDING"?item.reviewPackageId!==null&&item.decision===null:item.decision===filter)),[data.reviewFamilies,filter]);
  function toggle(id:string){setFeedback(null);setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id])}
  async function create(event:FormEvent){event.preventDefault();if(!selectedSnapshot)return;setPending(true);setFeedback(null);const family=await createKeywordReviewFamily({projectId,snapshotId:selectedSnapshot,normalizedFormIds:selected,label,rationale,version:1});if(!family.ok){setFeedback(family);setPending(false);return}const pkg=await createKeywordReviewPackage({projectId,snapshotId:selectedSnapshot,familyDraftIds:[family.data.id],packageVersion:data.nextPackageVersion});setFeedback(pkg);setPending(false);if(pkg.ok){setSelected([]);setLabel("");setRationale("");onChanged()}}
  async function packageFamily(familyId:string,snapshotId:string){setPending(true);setFeedback(null);const result=await createKeywordReviewPackage({projectId,snapshotId,familyDraftIds:[familyId],packageVersion:data.nextPackageVersion});setFeedback(result);setPending(false);if(result.ok)onChanged()}
  async function decide(familyId:string,reviewPackageId:string,decision:KeywordReviewDecision){setPending(true);setFeedback(null);const note=notes[familyId]?.trim();const result=await decideKeywordReview({projectId,familyDraftId:familyId,reviewPackageId,decision,...(note?{note}:{})});setFeedback(result);setPending(false);if(result.ok)onChanged()}
  return <div className="cp-stack">
    <section className="cp-section"><h2>人工确认进度</h2><p className="cp-placeholder-note">导入只代表资料已入库。只有完成关键词组整理并留下人工决定后，才会计入确认结果。</p><div className="cp-metric-grid">
      <button type="button" className="cp-card" onClick={()=>setFilter("PENDING")}><p className="cp-card-value">{data.totals.pendingReview}</p><p className="cp-card-label">待处理</p></button>
      <button type="button" className="cp-card" onClick={()=>setFilter("CONFIRMED")}><p className="cp-card-value">{data.totals.confirmed}</p><p className="cp-card-label">已确认</p></button>
      <button type="button" className="cp-card" onClick={()=>setFilter("CHANGES_REQUESTED")}><p className="cp-card-value">{data.totals.changesRequested}</p><p className="cp-card-label">需要修改</p></button>
      <button type="button" className="cp-card" onClick={()=>setFilter("REJECTED")}><p className="cp-card-value">{data.totals.rejected}</p><p className="cp-card-label">未通过</p></button>
    </div>{filter!=="ALL"?<button type="button" className="cp-button cp-button-secondary" onClick={()=>setFilter("ALL")}>查看全部审核记录</button>:null}</section>
    <section className="cp-section"><h2>整理待审核关键词组</h2>{data.keywords.length===0?<p className="cp-list-row cp-list-empty">请先导入关键词资料，再按同一数据版本选择需要共同审核的关键词。</p>:<form className="cp-form" onSubmit={create}><div className="cp-table-wrap"><table className="cp-data-table"><thead><tr><th>选择</th><th>标准化词</th><th>种子词</th><th>数据版本</th></tr></thead><tbody>{data.keywords.map(row=>{const disabled=!!selectedSnapshot&&row.snapshotId!==selectedSnapshot;return <tr key={row.normalizedFormId}><td><input aria-label={`选择 ${row.normalizedKeyword}`} type="checkbox" checked={selected.includes(row.normalizedFormId)} disabled={disabled||pending} onChange={()=>toggle(row.normalizedFormId)}/></td><td>{row.normalizedKeyword}</td><td>{row.seedKeyword}</td><td>第 {row.snapshotVersion} 版</td></tr>})}</tbody></table></div><label><span className="cp-field-label">关键词组名称</span><input className="cp-input" value={label} onChange={event=>setLabel(event.target.value)} required placeholder="例如：品牌核心服务"/></label><label><span className="cp-field-label">分组依据</span><textarea className="cp-input" value={rationale} onChange={event=>setRationale(event.target.value)} required placeholder="说明这些关键词为什么属于同一用户意图"/></label><button className="cp-button cp-button-primary" type="submit" disabled={pending||selected.length===0}>生成并提交审核</button></form>}<ActionFeedback pending={pending} result={feedback} successText="操作已保存，刷新或重新登录后仍可查看。"/></section>
    <section className="cp-section"><h2>审核记录</h2>{data.reviewFamilies.length===0?<p className="cp-list-row cp-list-empty">暂无人工审核记录。导入记录不会自动变成已确认结果。</p>:families.length===0?<p className="cp-list-row cp-list-empty">当前筛选条件下没有审核记录。</p>:<div className="cp-stack">{families.map(item=><article className="cp-card" key={item.id}><div className="cp-card-head"><div><h3>{item.label}</h3><p>第 {item.snapshotVersion} 版 · {item.keywords.join("、")}</p></div><span className="cp-status">{reviewText(item.decision,item.reviewPackageId!==null)}</span></div><p>{item.rationale}</p>{item.note?<p>处理说明：{item.note}</p>:null}{!item.reviewPackageId?<button type="button" className="cp-button" disabled={pending} onClick={()=>packageFamily(item.id,item.snapshotId)}>提交审核</button>:item.decision===null?<div className="cp-stack"><label><span className="cp-field-label">修改或未通过时必须填写说明</span><textarea className="cp-input" value={notes[item.id]??""} onChange={event=>setNotes(current=>({...current,[item.id]:event.target.value}))}/></label><div className="cp-actions"><button className="cp-button cp-button-primary" type="button" disabled={pending} onClick={()=>decide(item.id,item.reviewPackageId!,"CONFIRMED")}>确认</button><button className="cp-button" type="button" disabled={pending||!notes[item.id]?.trim()} onClick={()=>decide(item.id,item.reviewPackageId!,"CHANGES_REQUESTED")}>要求修改</button><button className="cp-button" type="button" disabled={pending||!notes[item.id]?.trim()} onClick={()=>decide(item.id,item.reviewPackageId!,"REJECTED")}>不通过</button></div></div>:null}</article>)}</div>}</section>
  </div>
}
