/** AGENCY_DELIVERY_AND_GROWTH_V1 — reconstructed P0 operating contract. */
export type AgencyWorkflowStage="CLIENT_PROFILE"|"PROJECT_PROFILE"|"ENTERPRISE_KNOWLEDGE"|"ACCOUNT_AUTHORIZATION"|"BAIDU_KEYWORDS"|"AI_EXPANSION"|"USER_QUESTION_CONFIRMATION"|"CONTENT_TASK"|"CONTENT_REVIEW"|"CHINA_AI_PROBE"|"REPORT"|"DELIVERY"|"RETROSPECTIVE";
export type AgencyWorkflowStatus="NOT_STARTED"|"IN_PROGRESS"|"WAITING_CLIENT"|"BLOCKED"|"COMPLETED";
/** Main-system order. CHINA_AI_PROBE remains a legacy/prototype event value but is not a delivery prerequisite. */
export const AGENCY_WORKFLOW_ORDER:readonly AgencyWorkflowStage[]=["CLIENT_PROFILE","PROJECT_PROFILE","ENTERPRISE_KNOWLEDGE","ACCOUNT_AUTHORIZATION","BAIDU_KEYWORDS","AI_EXPANSION","USER_QUESTION_CONFIRMATION","CONTENT_TASK","CONTENT_REVIEW","REPORT","DELIVERY","RETROSPECTIVE"];
export interface AgencyScope{readonly agencyOrganizationId:string;readonly clientOrganizationId:string;readonly projectId:string}
export interface AgencyWorkflowEvent extends AgencyScope{readonly id:string;readonly stage:AgencyWorkflowStage;readonly fromStatus:AgencyWorkflowStatus;readonly toStatus:AgencyWorkflowStatus;readonly actorUserId:string;readonly reason:string;readonly occurredAt:string}
export type AgencyPendingTaskKind="COMPLETE_KNOWLEDGE"|"CONFIRM_KEYWORDS"|"CONFIRM_QUESTIONS"|"REVIEW_CONTENT"|"RUN_PROBE"|"DELIVER_PROJECT"|"RESOLVE_ACCOUNT";
export interface AgencyPendingTask extends AgencyScope{readonly kind:AgencyPendingTaskKind;readonly count:number}
export interface AgencyDeliveryStatus extends AgencyScope{readonly status:"NOT_READY"|"READY"|"DELIVERED";readonly deliveredAt:null|string}
export interface AgencyClientProgress extends AgencyScope{readonly clientName:string;readonly projectName:string;readonly currentStage:AgencyWorkflowStage;readonly completedStageCount:number;readonly totalStageCount:number;readonly pendingTasks:readonly AgencyPendingTask[];readonly delivery:AgencyDeliveryStatus}
export interface AgencyQualitySummary{readonly reviewedContentCount:number;readonly passedContentCount:number;readonly rejectedContentCount:number|null;readonly failedProbeCount:number|null}
export interface AgencyAccountUsageSummary{readonly assignedAccountCount:number;readonly abnormalAccountCount:number;readonly operationCount:number;readonly failedOperationCount:number}
export interface AgencyPortfolioSummary{readonly agencyOrganizationId:string;readonly authorizedClientCount:number;readonly activeProjectCount:number;readonly clientsNeedingKnowledge:number;readonly clientsNeedingKeywordConfirmation:number;readonly questionsAwaitingConfirmation:number;readonly contentAwaitingReview:number;readonly probeTasksPending:number|null;readonly projectsAwaitingDelivery:number;readonly completedDeliveries:number;readonly abnormalAccounts:number;readonly abnormalProjects:number;readonly overdueTasks:number|null;readonly quality:AgencyQualitySummary;readonly accountUsage:AgencyAccountUsageSummary;readonly clients:readonly AgencyClientProgress[]}
export interface PlatformAgencyAggregate{readonly agencyOrganizationId:string;readonly authorizedClientCount:number;readonly activeProjectCount:number;readonly clientsNeedingKnowledge:number;readonly clientsNeedingKeywordConfirmation:number;readonly contentAwaitingReview:number;readonly probeTasksPending:number|null;readonly projectsAwaitingDelivery:number;readonly completedDeliveries:number;readonly abnormalAccounts:number;readonly abnormalProjects:number;readonly quality:AgencyQualitySummary}
