import{AGENCY_WORKFLOW_ORDER,type AgencyClientProgress,type AgencyPendingTask,type AgencyPortfolioSummary,type PlatformAgencyAggregate}from"./contracts.js";import{firstIncompleteStage}from"./state-machine.js";import type{AgencyDeliveryReadPort,AgencyProjectFact}from"./ports.js";
function task(f:AgencyProjectFact,kind:AgencyPendingTask["kind"],count:number|null):AgencyPendingTask|null{return count!==null&&count>0?{agencyOrganizationId:f.agencyOrganizationId,clientOrganizationId:f.clientOrganizationId,projectId:f.projectId,kind,count}:null}
export async function buildAgencyPortfolioSummary(agencyOrganizationId:string,port:AgencyDeliveryReadPort):Promise<AgencyPortfolioSummary>{
 const authorized=await port.listAuthorizedClients(agencyOrganizationId);const ids=new Set(authorized.map(x=>x.clientOrganizationId));const facts:AgencyProjectFact[]=[];
 for(const client of authorized){const rows=await port.listProjectFacts(agencyOrganizationId,client.clientOrganizationId);facts.push(...rows.filter(row=>row.agencyOrganizationId===agencyOrganizationId&&row.clientOrganizationId===client.clientOrganizationId));}
 const clients:AgencyClientProgress[]=facts.map(f=>{const client=authorized.find(x=>x.clientOrganizationId===f.clientOrganizationId)!;const pending=[task(f,"COMPLETE_KNOWLEDGE",f.missingKnowledgeCount),task(f,"CONFIRM_KEYWORDS",f.keywordConfirmationCount),task(f,"CONFIRM_QUESTIONS",f.questionConfirmationCount),task(f,"REVIEW_CONTENT",f.contentReviewCount),task(f,"DELIVER_PROJECT",f.deliveryStatus==="READY"?1:0)].filter((x):x is AgencyPendingTask=>x!==null);return{agencyOrganizationId,clientOrganizationId:f.clientOrganizationId,projectId:f.projectId,clientName:client.clientName,projectName:f.projectName,currentStage:firstIncompleteStage(f.workflowStatuses,AGENCY_WORKFLOW_ORDER),completedStageCount:AGENCY_WORKFLOW_ORDER.filter(stage=>f.workflowStatuses.get(stage)==="COMPLETED").length,totalStageCount:AGENCY_WORKFLOW_ORDER.length,pendingTasks:pending,delivery:{agencyOrganizationId,clientOrganizationId:f.clientOrganizationId,projectId:f.projectId,status:f.deliveryStatus,deliveredAt:f.deliveredAt}}});
 const accounts=(await port.listAccountFacts(agencyOrganizationId,[...ids])).filter(a=>a.clientOrganizationId===null||ids.has(a.clientOrganizationId));const uniqueAccounts=new Map(accounts.map(a=>[a.accountId,a]));const accountRows=[...uniqueAccounts.values()];const sum=(pick:(f:AgencyProjectFact)=>number)=>facts.reduce((n,f)=>n+pick(f),0);const nullableSum=(pick:(f:AgencyProjectFact)=>number|null)=>facts.some(f=>pick(f)===null)?null:facts.reduce((n,f)=>n+(pick(f)??0),0);const quality={reviewedContentCount:sum(f=>f.reviewedContentCount),passedContentCount:sum(f=>f.passedContentCount),rejectedContentCount:nullableSum(f=>f.rejectedContentCount),failedProbeCount:nullableSum(f=>f.failedProbeCount)};
 return{agencyOrganizationId,authorizedClientCount:ids.size,activeProjectCount:facts.filter(f=>f.active).length,clientsNeedingKnowledge:new Set(facts.filter(f=>f.missingKnowledgeCount>0).map(f=>f.clientOrganizationId)).size,clientsNeedingKeywordConfirmation:new Set(facts.filter(f=>f.keywordConfirmationCount>0).map(f=>f.clientOrganizationId)).size,questionsAwaitingConfirmation:sum(f=>f.questionConfirmationCount),contentAwaitingReview:sum(f=>f.contentReviewCount),probeTasksPending:null,projectsAwaitingDelivery:facts.filter(f=>f.deliveryStatus==="READY").length,completedDeliveries:facts.filter(f=>f.deliveryStatus==="DELIVERED").length,abnormalAccounts:accountRows.filter(a=>a.abnormal).length,abnormalProjects:facts.filter(f=>f.hasBlockingFailure).length,overdueTasks:null,quality,accountUsage:{assignedAccountCount:accountRows.length,abnormalAccountCount:accountRows.filter(a=>a.abnormal).length,operationCount:accountRows.reduce((n,a)=>n+a.operationCount,0),failedOperationCount:accountRows.reduce((n,a)=>n+a.failedOperationCount,0)},clients};
}
export function toPlatformAgencyAggregate(v:AgencyPortfolioSummary):PlatformAgencyAggregate{return{agencyOrganizationId:v.agencyOrganizationId,authorizedClientCount:v.authorizedClientCount,activeProjectCount:v.activeProjectCount,clientsNeedingKnowledge:v.clientsNeedingKnowledge,clientsNeedingKeywordConfirmation:v.clientsNeedingKeywordConfirmation,contentAwaitingReview:v.contentAwaitingReview,probeTasksPending:v.probeTasksPending,projectsAwaitingDelivery:v.projectsAwaitingDelivery,completedDeliveries:v.completedDeliveries,abnormalAccounts:v.abnormalAccounts,abnormalProjects:v.abnormalProjects,quality:v.quality}}
