import {describe,expect,it} from "vitest";
import type {DemandEvidence,KeywordDataset,KeywordDecisionRecord,KeywordImportBatch,KeywordRecord,KeywordReviewPackage,KeywordScope} from "../../../src/runtime/generic-keywords/contracts.js";
import type {GenericKeywordRepository} from "../../../src/runtime/generic-keywords/ports.js";
import {GenericKeywordService} from "../../../src/runtime/generic-keywords/service.js";
import {parseGenericKeywordImport} from "../../../src/runtime/generic-keywords/importer.js";

class Repo implements GenericKeywordRepository{
  datasets:KeywordDataset[]=[];batches:KeywordImportBatch[]=[];records:KeywordRecord[]=[];evidence:DemandEvidence[]=[];packages:KeywordReviewPackage[]=[];decisions:KeywordDecisionRecord[]=[];
  async addDataset(v:KeywordDataset){this.datasets.push(v)}async getDataset(s:KeywordScope,id:string){return this.datasets.find(v=>v.id===id&&v.clientOrganizationId===s.clientOrganizationId&&v.projectId===s.projectId)}async addImportBatch(v:KeywordImportBatch){this.batches.push(v)}async addRecords(v:readonly KeywordRecord[]){this.records.push(...v)}async addDemandEvidence(v:readonly DemandEvidence[]){this.evidence.push(...v)}async listRecords(s:KeywordScope,id:string){return this.records.filter(v=>v.datasetId===id&&v.clientOrganizationId===s.clientOrganizationId&&v.projectId===s.projectId)}async addReviewPackage(v:KeywordReviewPackage){this.packages.push(v)}async getReviewPackage(s:KeywordScope,id:string){return this.packages.find(v=>v.id===id&&v.clientOrganizationId===s.clientOrganizationId&&v.projectId===s.projectId)}async addDecision(v:KeywordDecisionRecord){this.decisions.push(v)}
  async archiveDataset(s:KeywordScope,id:string){const i=this.datasets.findIndex(v=>v.id===id&&v.clientOrganizationId===s.clientOrganizationId&&v.projectId===s.projectId&&v.status==="ACTIVE");if(i<0)return false;this.datasets[i]={...this.datasets[i]!,status:"ARCHIVED"};return true}
  async saveImportedBatch(b:KeywordImportBatch,r:readonly KeywordRecord[],e:readonly DemandEvidence[]){this.batches.push(b);this.records.push(...r);this.evidence.push(...e)}
}
const scope={clientOrganizationId:"client-a",projectId:"project-a"};let seq=0;const service=(repo:Repo)=>new GenericKeywordService(repo,{next:()=>`id-${++seq}`},()=>"2026-07-20T00:00:00.000Z");
describe("GENERIC_KEYWORD_CORE_V1",()=>{
  it("adds a manual keyword without fabricating demand evidence",async()=>{const repo=new Repo(),s=service(repo);const ds=await s.createDataset({...scope,name:"人工词",source:"MANUAL",createdByUserId:"u"});const record=await s.addManualKeyword({...scope,datasetId:ds.id,keyword:" GEO 服务 ",createdByUserId:"u"});expect(record.source).toBe("MANUAL");expect(record.normalizedKeyword).toBe("geo 服务");expect(repo.evidence).toEqual([]);});
  it("imports a generic file with optional fields and creates evidence only for complete real-source fields",async()=>{const repo=new Repo(),s=service(repo);const ds=await s.createDataset({...scope,name:"历史需求",source:"CUSTOMER_HISTORY",createdByUserId:"u"});const parsed=parseGenericKeywordImport("history.csv",Buffer.from("keyword,category,metric_kind,metric_value,observed_at,source_reference\nGEO 服务,服务词,SEARCH_COUNT,12,2026-07-01T00:00:00Z,crm-export-7\n仅普通词,,,,,\n"));const out=await s.importFile({...scope,datasetId:ds.id,source:"CUSTOMER_HISTORY",fileName:"history.csv",parsed,importedByUserId:"u"});expect(out.records).toHaveLength(2);expect(out.evidence).toHaveLength(1);expect(out.evidence[0]).toMatchObject({metricKind:"SEARCH_COUNT",metricValue:12,sourceReference:"crm-export-7"});});
  it("rejects metric values that lack provenance instead of confirming demand",async()=>{const repo=new Repo(),s=service(repo);const ds=await s.createDataset({...scope,name:"通用文件",source:"GENERIC_FILE",createdByUserId:"u"});const parsed=parseGenericKeywordImport("words.csv",Buffer.from("keyword,metric_value\nGEO,10\n"));await expect(s.importFile({...scope,datasetId:ds.id,source:"GENERIC_FILE",fileName:"words.csv",parsed,importedByUserId:"u"})).rejects.toThrow("INCOMPLETE_DEMAND_EVIDENCE");expect(repo.evidence).toEqual([]);});
  it("keeps tenant scope when reviewing records",async()=>{const repo=new Repo(),s=service(repo);const ds=await s.createDataset({...scope,name:"人工词",source:"MANUAL",createdByUserId:"u"});const record=await s.addManualKeyword({...scope,datasetId:ds.id,keyword:"GEO",createdByUserId:"u"});await expect(s.createReviewPackage({clientOrganizationId:"other",projectId:scope.projectId,datasetId:ds.id,keywordRecordIds:[record.id],version:1,submittedByUserId:"u"})).rejects.toThrow("KEYWORD_DATASET_NOT_FOUND");});
});
