import {dirname,join} from "node:path";import {fileURLToPath} from "node:url";import {afterAll,beforeAll,beforeEach,describe,expect,it} from "vitest";
import type {OrganizationType,PlatformRole} from "../../../src/contracts/tenancy/entities.js";import {loadDatabaseConfig} from "../../../src/persistence/config.js";import type {DatabasePort} from "../../../src/persistence/database-port.js";import {applyMigrations} from "../../../src/persistence/pg/migrator.js";import {createPgDatabase} from "../../../src/persistence/pg/pg-database.js";import {__setAuthRuntimeForTests,createAuthRuntime,type AuthRuntime} from "../../../src/runtime/auth/runtime-context.js";import {__setGeoRuntimeForTests,createGeoRuntime} from "../../../src/runtime/geo/runtime-context.js";
import {POST as loginRoute} from "../../../src/app/api/auth/login/route.js";import {POST as datasetsRoute} from "../../../src/app/api/generic-keywords/datasets/route.js";import {POST as recordsRoute} from "../../../src/app/api/generic-keywords/datasets/[datasetId]/records/route.js";import {POST as archiveRoute} from "../../../src/app/api/generic-keywords/datasets/[datasetId]/archive/route.js";import {POST as importsRoute} from "../../../src/app/api/generic-keywords/imports/route.js";import {POST as packagesRoute} from "../../../src/app/api/generic-keywords/review-packages/route.js";import {POST as decisionsRoute} from "../../../src/app/api/generic-keywords/review-packages/[id]/decisions/route.js";import {GET as workspaceRoute} from "../../../src/app/api/generic-keywords/projects/[projectId]/route.js";import {TEST_LOGIN_PASSWORD,TEST_LOGIN_PASSWORD_HASH} from "../../helpers/auth-credentials.js";
const config=loadDatabaseConfig({test:true}),migrations=join(dirname(fileURLToPath(import.meta.url)),"..","..","..","migrations");let db:DatabasePort,auth:AuthRuntime;
async function identity(email:string,type:OrganizationType,role:PlatformRole,key:string){const user=await db.query<{id:string}>(`INSERT INTO "user"(email,password_hash) VALUES($1,$2) RETURNING id`,[email,TEST_LOGIN_PASSWORD_HASH]);const userId=user.rows[0]!.id;const organization=await auth.repos.organizations.createIdempotent({type,displayName:key,idempotencyKey:key,createdByUserId:userId});await auth.repos.memberships.create({userId,organizationId:organization.id,role});return{userId,organizationId:organization.id,email};}
async function login(email:string){const response=await loginRoute(post("http://test/api/auth/login","",{email,password:TEST_LOGIN_PASSWORD}));expect(response.status).toBe(200);return response.headers.get("set-cookie")!.split(";")[0]!;}
const post=(url:string,cookie:string,body:unknown)=>new Request(url,{method:"POST",headers:{...(cookie?{cookie}:{}),"content-type":"application/json"},body:JSON.stringify(body)});const body=async(r:Response|undefined)=>(await r!.json()).data;
describe.skipIf(config===null)("generic keyword authorized HTTP routes",()=>{beforeAll(async()=>{db=createPgDatabase({connectionString:config!.connectionString,max:6});await applyMigrations(db,migrations);auth=createAuthRuntime(db);__setAuthRuntimeForTests(auth);__setGeoRuntimeForTests(createGeoRuntime(db));});afterAll(async()=>{__setAuthRuntimeForTests(null);__setGeoRuntimeForTests(null);if(db)await db.close();});beforeEach(async()=>{await db.query(`TRUNCATE demand_evidence,keyword_decision_v2,keyword_review_package_item_v2,keyword_review_package_v2,keyword_record,keyword_import_batch,keyword_dataset,keyword_human_review_record,keyword_human_review_package_item,keyword_human_review_package,keyword_family_draft_member,keyword_family_draft,keyword_reference_snapshot,keyword_demand_observation,keyword_discovery,keyword_normalized_form,keyword_raw_observation,keyword_reference_source_import,agency_client_assignment,session,membership,project,organization,"user" RESTART IDENTITY CASCADE`);});
it("supports client, authorized agency and platform while rejecting unrelated clients and preserving refresh state",async()=>{const client=await identity("generic-client@example.test","CLIENT","CLIENT_OWNER","generic-client"),other=await identity("generic-other@example.test","CLIENT","CLIENT_OWNER","generic-other"),agency=await identity("generic-agency@example.test","AGENCY","AGENCY_OWNER","generic-agency"),platform=await identity("generic-platform@example.test","PLATFORM","PLATFORM_SUPER_ADMIN","generic-platform");const project=await auth.repos.projects.create({clientOrganizationId:client.organizationId,name:"通用关键词项目",createdByUserId:client.userId});await auth.repos.agencyClientAssignments.assign({agencyOrganizationId:agency.organizationId,clientOrganizationId:client.organizationId,assignedByUserId:platform.userId});const [clientCookie,otherCookie,agencyCookie,platformCookie]=await Promise.all([login(client.email),login(other.email),login(agency.email),login(platform.email)]);
  const created=await datasetsRoute(post("http://test/api/generic-keywords/datasets",clientCookie,{projectId:project.id,name:"人工关键词",source:"MANUAL"}));expect(created!.status).toBe(200);const dataset=await body(created);
  const denied=await recordsRoute(post(`http://test/api/generic-keywords/datasets/${dataset.id}/records`,otherCookie,{projectId:project.id,keyword:"越权词"}),{params:Promise.resolve({datasetId:dataset.id})});expect(denied!.status).toBe(403);
  const added=await recordsRoute(post(`http://test/api/generic-keywords/datasets/${dataset.id}/records`,clientCookie,{projectId:project.id,keyword:"GEO 企业服务",category:"业务词"}),{params:Promise.resolve({datasetId:dataset.id})});expect(added!.status).toBe(200);const record=await body(added);
  const agencyRead=await workspaceRoute(new Request(`http://test/api/generic-keywords/projects/${project.id}`,{headers:{cookie:agencyCookie}}),{params:Promise.resolve({projectId:project.id})});expect(agencyRead!.status).toBe(200);expect((await body(agencyRead)).records).toHaveLength(1);
  const pkgResponse=await packagesRoute(post("http://test/api/generic-keywords/review-packages",agencyCookie,{projectId:project.id,datasetId:dataset.id,keywordRecordIds:[record.id],version:1}));expect(pkgResponse!.status).toBe(200);const pkg=await body(pkgResponse);
  const decision=await decisionsRoute(post(`http://test/api/generic-keywords/review-packages/${pkg.id}/decisions`,platformCookie,{projectId:project.id,keywordRecordId:record.id,decision:"REJECTED",note:"与当前业务目标不符"}),{params:Promise.resolve({id:pkg.id})});expect(decision!.status).toBe(200);
  const fileDatasetResponse=await datasetsRoute(post("http://test/api/generic-keywords/datasets",platformCookie,{projectId:project.id,name:"客户历史需求",source:"CUSTOMER_HISTORY"}));const fileDataset=await body(fileDatasetResponse);const csv=Buffer.from("keyword,metric_kind,metric_value,observed_at,source_reference\nGEO 代运营,SEARCH_COUNT,21,2026-07-20T00:00:00Z,crm-batch-9\n").toString("base64");const imported=await importsRoute(post("http://test/api/generic-keywords/imports",platformCookie,{projectId:project.id,datasetId:fileDataset.id,source:"CUSTOMER_HISTORY",fileName:"history.csv",base64:csv}));expect(imported!.status).toBe(200);const importedData=await body(imported);expect(importedData).toMatchObject({acceptedCount:1,evidenceCount:1});const filtered=await workspaceRoute(new Request(`http://test/api/generic-keywords/projects/${project.id}?source=CUSTOMER_HISTORY&batchId=${importedData.batchId}`,{headers:{cookie:platformCookie}}),{params:Promise.resolve({projectId:project.id})});expect((await body(filtered)).records).toHaveLength(1);
  const archived=await archiveRoute(post(`http://test/api/generic-keywords/datasets/${dataset.id}/archive`,clientCookie,{projectId:project.id}),{params:Promise.resolve({datasetId:dataset.id})});expect(archived!.status).toBe(200);expect((await body(archived)).status).toBe("ARCHIVED");
  const refreshedCookie=await login(client.email);const refreshed=await workspaceRoute(new Request(`http://test/api/generic-keywords/projects/${project.id}`,{headers:{cookie:refreshedCookie}}),{params:Promise.resolve({projectId:project.id})});const data=await body(refreshed);expect(data.datasets.find((x:any)=>x.id===dataset.id)).toMatchObject({status:"ARCHIVED",nextReviewPackageVersion:2});expect(data.decisions[0]).toMatchObject({keywordRecordId:record.id,decision:"REJECTED"});expect(data.evidence[0]).toMatchObject({metricKind:"SEARCH_COUNT",metricValue:21});
});});
