import { dirname,join } from "node:path";import { fileURLToPath } from "node:url";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
import type { OrganizationType,PlatformRole } from "../../../src/contracts/tenancy/entities.js";
import { loadDatabaseConfig } from "../../../src/persistence/config.js";import type { DatabasePort } from "../../../src/persistence/database-port.js";import { applyMigrations } from "../../../src/persistence/pg/migrator.js";import { createPgDatabase } from "../../../src/persistence/pg/pg-database.js";
import { __setAuthRuntimeForTests,createAuthRuntime,type AuthRuntime } from "../../../src/runtime/auth/runtime-context.js";import { __setGeoRuntimeForTests,createGeoRuntime } from "../../../src/runtime/geo/runtime-context.js";
import { POST as loginRoute } from "../../../src/app/api/auth/login/route.js";import { POST as importRoute } from "../../../src/app/api/keywords/imports/route.js";import { GET as overviewRoute } from "../../../src/app/api/keywords/projects/[projectId]/overview/route.js";import { POST as familyRoute } from "../../../src/app/api/keywords/family-drafts/route.js";import { POST as packageRoute } from "../../../src/app/api/keywords/review-packages/route.js";import { POST as decisionRoute } from "../../../src/app/api/keywords/review-packages/[id]/decisions/route.js";
import { TEST_LOGIN_PASSWORD,TEST_LOGIN_PASSWORD_HASH } from "../../helpers/auth-credentials.js";

const testConfig=loadDatabaseConfig({test:true});const migrationsDir=join(dirname(fileURLToPath(import.meta.url)),"..","..","..","migrations");let db:DatabasePort;let auth:AuthRuntime;
async function identity(email:string,type:OrganizationType,role:PlatformRole,key:string){const user=await db.query<{id:string}>(`INSERT INTO "user"(email,password_hash) VALUES($1,$2) RETURNING id`,[email,TEST_LOGIN_PASSWORD_HASH]);const userId=user.rows[0]!.id;const organization=await auth.repos.organizations.createIdempotent({type,displayName:key,idempotencyKey:key,createdByUserId:userId});await auth.repos.memberships.create({userId,organizationId:organization.id,role});return{userId,organizationId:organization.id,email}}
async function login(email:string){const response=await loginRoute(new Request("http://test/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password:TEST_LOGIN_PASSWORD})}));expect(response.status).toBe(200);return response.headers.get("set-cookie")!.split(";")[0]!}
const post=(url:string,cookie:string,body:unknown)=>new Request(url,{method:"POST",headers:{cookie,"content-type":"application/json"},body:JSON.stringify(body)});

describe.skipIf(testConfig===null)("百度关键词人工决策工作台真实路由",()=>{
  beforeAll(async()=>{db=createPgDatabase({connectionString:testConfig!.connectionString,max:6});await applyMigrations(db,migrationsDir);auth=createAuthRuntime(db);__setAuthRuntimeForTests(auth);__setGeoRuntimeForTests(createGeoRuntime(db))});
  afterAll(async()=>{__setAuthRuntimeForTests(null);__setGeoRuntimeForTests(null);if(db)await db.close()});
  beforeEach(async()=>{await db.query(`TRUNCATE keyword_human_review_record,keyword_human_review_package_item,keyword_human_review_package,keyword_family_draft_member,keyword_family_draft,keyword_reference_snapshot,keyword_demand_observation,keyword_discovery,keyword_normalized_form,keyword_raw_observation,keyword_reference_source_import,agency_client_assignment,session,membership,project,organization,"user" RESTART IDENTITY CASCADE`)});

  it("客户导入与整理、授权代理商提交、平台决定，并在刷新和重登后保持项目隔离",async()=>{const client=await identity("kw-review-client@example.test","CLIENT","CLIENT_OWNER","kw-review-client");const other=await identity("kw-review-other@example.test","CLIENT","CLIENT_OWNER","kw-review-other");const agency=await identity("kw-review-agency@example.test","AGENCY","AGENCY_OWNER","kw-review-agency");const platform=await identity("kw-review-platform@example.test","PLATFORM","PLATFORM_SUPER_ADMIN","kw-review-platform");const project=await auth.repos.projects.create({clientOrganizationId:client.organizationId,name:"关键词项目",createdByUserId:client.userId});await auth.repos.agencyClientAssignments.assign({agencyOrganizationId:agency.organizationId,clientOrganizationId:client.organizationId,assignedByUserId:platform.userId});const [clientCookie,otherCookie,agencyCookie,platformCookie]=await Promise.all([login(client.email),login(other.email),login(agency.email),login(platform.email)]);
    const csv=Buffer.from("seed_keyword,keyword,demand_value,observed_at\nGEO,GEO 服务,19,2026-07-19T12:00:00.000Z\n").toString("base64");const imported=await importRoute(post("http://test/api/keywords/imports",clientCookie,{projectId:project.id,fileName:"baidu.csv",base64:csv}));expect(imported.status).toBe(200);const importedBody=await imported.json();
    const overview=(await overviewRoute(new Request(`http://test/api/keywords/projects/${project.id}/overview`,{headers:{cookie:clientCookie}}),{params:Promise.resolve({projectId:project.id})}))!;expect(overview.status).toBe(200);const overviewBody=await overview.json();const normalizedFormId=overviewBody.data.keywords[0].normalizedFormId;
    const denied=await familyRoute(post("http://test/api/keywords/family-drafts",otherCookie,{projectId:project.id,snapshotId:importedBody.data.snapshotId,normalizedFormIds:[normalizedFormId],label:"越权",rationale:"不应写入",version:1}));expect(denied.status).toBe(403);
    const family=await familyRoute(post("http://test/api/keywords/family-drafts",clientCookie,{projectId:project.id,snapshotId:importedBody.data.snapshotId,normalizedFormIds:[normalizedFormId],label:"核心服务",rationale:"客户人工整理为同一意图",version:1}));expect(family.status).toBe(200);const familyBody=await family.json();
    const pkg=await packageRoute(post("http://test/api/keywords/review-packages",agencyCookie,{projectId:project.id,snapshotId:importedBody.data.snapshotId,familyDraftIds:[familyBody.data.id],packageVersion:1}));expect(pkg.status).toBe(200);const pkgBody=await pkg.json();
    const decision=await decisionRoute(post(`http://test/api/keywords/review-packages/${pkgBody.data.id}/decisions`,platformCookie,{projectId:project.id,familyDraftId:familyBody.data.id,decision:"CONFIRMED"}),{params:Promise.resolve({id:pkgBody.data.id})});expect(decision.status).toBe(200);
    const reloggedCookie=await login(client.email);const persisted=(await overviewRoute(new Request(`http://test/api/keywords/projects/${project.id}/overview`,{headers:{cookie:reloggedCookie}}),{params:Promise.resolve({projectId:project.id})}))!;const persistedBody=await persisted.json();expect(persistedBody.data.reviewFamilies[0]).toMatchObject({label:"核心服务",decision:"CONFIRMED",reviewPackageId:pkgBody.data.id});expect(persistedBody.data.totals.confirmed).toBe(1);expect((await db.query(`SELECT 1 FROM keyword_human_review_record WHERE review_package_id=$1`,[pkgBody.data.id])).rowCount).toBe(1);
  });
});
