import { describe,expect,it } from "vitest";
import type { HumanReviewPackage,KeywordFamilyDraft,KeywordRawObservation,KeywordReferenceSnapshot,KeywordReferenceSourceImport,KeywordReviewRecord,KeywordScope } from "../../../src/runtime/keywords/contracts.js";
import type { PreparedKeywordImport } from "../../../src/runtime/keywords/normalization.js";
import type { KeywordRuntimeRepository } from "../../../src/runtime/keywords/ports.js";
import { KeywordReviewService } from "../../../src/runtime/keywords/review-service.js";

class FakeRepo implements KeywordRuntimeRepository {
  drafts=new Map<string,KeywordFamilyDraft>();packages=new Map<string,HumanReviewPackage>();records:KeywordReviewRecord[]=[];snapshots=new Map<string,KeywordReferenceSnapshot>();forms=new Map<string,string[]>();
  async savePreparedImport(_v:PreparedKeywordImport){return "CREATED" as const} async addImport(_v:KeywordReferenceSourceImport){} async findCompletedImportByManifest(_s:KeywordScope,_h:string){return undefined} async addRawObservations(_v:readonly KeywordRawObservation[]){}
  async addSnapshot(v:KeywordReferenceSnapshot){this.snapshots.set(v.id,v)} async getSnapshot(s:KeywordScope,id:string){const v=this.snapshots.get(id);return v?.clientOrganizationId===s.clientOrganizationId&&v.projectId===s.projectId?v:undefined} async listNormalizedFormIdsForSnapshot(s:KeywordScope,id:string){return (await this.getSnapshot(s,id))?this.forms.get(id)??[]:[]}
  async addFamilyDraft(v:KeywordFamilyDraft){this.drafts.set(v.id,v)} async getFamilyDraft(s:KeywordScope,id:string){const v=this.drafts.get(id);return v?.clientOrganizationId===s.clientOrganizationId&&v.projectId===s.projectId?v:undefined} async addReviewPackage(v:HumanReviewPackage){this.packages.set(v.id,v)} async getReviewPackage(s:KeywordScope,id:string){const v=this.packages.get(id);return v?.clientOrganizationId===s.clientOrganizationId&&v.projectId===s.projectId?v:undefined} async addReviewRecord(v:KeywordReviewRecord){this.records.push(v)} async listReviewRecords(s:KeywordScope,p:string){return this.records.filter(x=>x.clientOrganizationId===s.clientOrganizationId&&x.projectId===s.projectId&&x.reviewPackageId===p)}
}
const scope={clientOrganizationId:"client-a",projectId:"project-a"};const now="2026-07-19T00:00:00.000Z";function ids(){let n=0;return{next:()=>`id-${++n}`}}
function snapshot():KeywordReferenceSnapshot{return {...scope,id:"snapshot-1",importId:"import-1",snapshotVersion:1,manifestHash:"a".repeat(64),rawObservationCount:1,normalizedFormCount:1,demandObservationCount:0,sealedAt:now}}

describe("keyword human review package",()=>{
  it("creates a submitted family only from explicitly selected forms in the same scoped snapshot",async()=>{const repo=new FakeRepo();await repo.addSnapshot(snapshot());repo.forms.set("snapshot-1",["form-1"]);const service=new KeywordReviewService(repo,ids(),()=>now);const family=await service.createSubmittedFamily({...scope,snapshotId:"snapshot-1",normalizedFormIds:["form-1"],label:"核心需求",rationale:"用户人工确认属于同一意图",createdByUserId:"author",version:1});expect(family).toMatchObject({status:"SUBMITTED",normalizedFormIds:["form-1"],label:"核心需求"});expect(repo.drafts.get(family.id)).toEqual(family)});
  it("rejects cross-snapshot members instead of treating raw imports as reviewed",async()=>{const repo=new FakeRepo();await repo.addSnapshot(snapshot());repo.forms.set("snapshot-1",["form-1"]);const service=new KeywordReviewService(repo,ids(),()=>now);await expect(service.createSubmittedFamily({...scope,snapshotId:"snapshot-1",normalizedFormIds:["form-other"],label:"错误分组",rationale:"不属于本快照",createdByUserId:"author",version:1})).rejects.toThrow("NORMALIZED_FORM_NOT_IN_SNAPSHOT");await expect(service.createSubmittedFamily({...scope,clientOrganizationId:"client-b",snapshotId:"snapshot-1",normalizedFormIds:["form-1"],label:"越权",rationale:"越权",createdByUserId:"author",version:1})).rejects.toThrow("SNAPSHOT_NOT_FOUND")});
  it("requires submitted drafts and records CONFIRMED only with an explicit reviewer",async()=>{const repo=new FakeRepo();repo.drafts.set("draft-1",{...scope,id:"draft-1",snapshotId:"snapshot-1",version:1,label:"GEO",normalizedFormIds:["form-1"],rationale:"same intent",status:"SUBMITTED",createdByUserId:"author",createdAt:now});const service=new KeywordReviewService(repo,ids(),()=>now);const pkg=await service.createPackage({...scope,snapshotId:"snapshot-1",familyDraftIds:["draft-1"],submittedByUserId:"author",packageVersion:1});const decision=await service.decide({...scope,reviewPackageId:pkg.id,familyDraftId:"draft-1",decision:"CONFIRMED",reviewerUserId:"reviewer-human"});expect(decision).toMatchObject({decision:"CONFIRMED",reviewerUserId:"reviewer-human",decidedAt:now});expect(repo.records).toHaveLength(1)});
  it("never silently confirms, rejects missing notes, duplicate decisions and cross-tenant packages",async()=>{const repo=new FakeRepo();repo.drafts.set("draft-1",{...scope,id:"draft-1",snapshotId:"snapshot-1",version:1,label:"GEO",normalizedFormIds:["form-1"],rationale:"same intent",status:"SUBMITTED",createdByUserId:"author",createdAt:now});const service=new KeywordReviewService(repo,ids(),()=>now);const pkg=await service.createPackage({...scope,snapshotId:"snapshot-1",familyDraftIds:["draft-1"],submittedByUserId:"author",packageVersion:1});await expect(service.decide({...scope,reviewPackageId:pkg.id,familyDraftId:"draft-1",decision:"REJECTED",reviewerUserId:"human"})).rejects.toThrow("REVIEW_NOTE_REQUIRED");await service.decide({...scope,reviewPackageId:pkg.id,familyDraftId:"draft-1",decision:"CHANGES_REQUESTED",reviewerUserId:"human",note:"split intent"});await expect(service.decide({...scope,reviewPackageId:pkg.id,familyDraftId:"draft-1",decision:"CONFIRMED",reviewerUserId:"human"})).rejects.toThrow("REVIEW_ITEM_ALREADY_DECIDED");await expect(service.decide({clientOrganizationId:"client-b",projectId:"project-b",reviewPackageId:pkg.id,familyDraftId:"draft-1",decision:"CONFIRMED",reviewerUserId:"human"})).rejects.toThrow("REVIEW_ITEM_NOT_FOUND")});
});
