import {describe,expect,it} from "vitest";
import type {AuthorizationContext} from "../../../src/contracts/tenancy/entities.js";
import {AccountOperationService} from "../../../src/runtime/accounts/operation-service.js";
import type {AccountAssignment,AccountAuthorization,AccountHealth,AccountOperationResult,AccountOperationTask,AccountUsageRecord,PlatformAccount} from "../../../src/runtime/accounts/entities.js";
import type {AccountRepository} from "../../../src/runtime/accounts/ports.js";

class LedgerRepo implements AccountRepository{account:PlatformAccount={id:"a1",platformCode:"DOUBAO",accountType:"AI_PLATFORM_ACCOUNT",ownership:"PLATFORM_OWNED",agencyOrganizationId:null,clientOrganizationId:null,displayLabel:"账号",secretReference:null,credentialStatus:"NOT_CONFIGURED",lastVerifiedAt:null,status:"ACTIVE",operationMode:"MANUAL_OPERATION",createdByUserId:"u",createdAt:"now",updatedAt:"now"};assignment:AccountAssignment={id:"s1",accountId:"a1",projectId:"p1",clientOrganizationId:"c1",operatorUserId:"op",status:"ACTIVE",assignedByUserId:"u",assignedAt:"now",revokedAt:null};tasks:AccountOperationTask[]=[];results:AccountOperationResult[]=[];usage:AccountUsageRecord[]=[];
async createAccount():Promise<PlatformAccount>{return this.account;}async findAccountById(id:string){return id==="a1"?this.account:null;}async addAuthorization():Promise<AccountAuthorization>{throw 0;}async findActiveAuthorization():Promise<AccountAuthorization|null>{return null;}async revokeAuthorization():Promise<AccountAuthorization>{throw 0;}async addAssignment():Promise<AccountAssignment>{return this.assignment;}async findActiveAssignment(a:string,p:string){return a==="a1"&&p==="p1"?this.assignment:null;}async addHealth():Promise<AccountHealth>{throw 0;}async addUsage(i:Omit<AccountUsageRecord,"id">){const x={id:`u${this.usage.length}`,...i};this.usage.push(x);return x;}async createOperationTask(i:Omit<AccountOperationTask,"id"|"requestedAt"|"startedAt"|"completedAt">){const x={id:`t${this.tasks.length+1}`,...i,requestedAt:"now",startedAt:null,completedAt:null};this.tasks.push(x);return x;}async completeOperationTask(id:string,status:"SUCCEEDED"|"FAILED",at:string){const x=this.tasks.find(t=>t.id===id)!;const done={...x,status,completedAt:at};this.tasks[this.tasks.indexOf(x)]=done;return done;}async findOperationTaskById(id:string){return this.tasks.find(t=>t.id===id)??null;}async addOperationResult(i:Omit<AccountOperationResult,"id"|"recordedAt">){if(this.results.some(x=>x.taskId===i.taskId))throw new Error("append-only duplicate");const x={id:`r${this.results.length+1}`,...i,recordedAt:"now"};this.results.push(x);return x;}}
const ctx:AuthorizationContext={actorUserId:"u",actorRole:"CLIENT_OWNER",organizationId:"c1",organizationType:"CLIENT",activeProjectId:"p1",activeClientOrganizationId:"c1",assignedClientOrganizationIds:[],allowedClientOrganizationIds:[],isPlatformAdmin:false,permissions:[]};
describe("account operation ledger",()=>{it("requires project assignment and appends a manual result and usage record",async()=>{const repo=new LedgerRepo();const audit:any[]=[];const svc=new AccountOperationService(repo,{append:async e=>{audit.push(e);}});const task=await svc.createTask(ctx,{accountId:"a1",projectId:"p1",clientOrganizationId:"c1",operationKind:"MANUAL_QUERY",operatorUserId:"op"});expect(task.operationMode).toBe("MANUAL_OPERATION");const result=await svc.recordResult(ctx,{taskId:task.id,status:"SUCCEEDED",resultSummary:"人工完成"});expect(result.status).toBe("SUCCEEDED");expect(repo.usage).toHaveLength(1);expect(audit).toHaveLength(2);await expect(svc.recordResult(ctx,{taskId:task.id,status:"SUCCEEDED"})).rejects.toThrow(/append-only/);expect(repo.results).toHaveLength(1);});it("denies an unassigned project and writes a denied audit",async()=>{const repo=new LedgerRepo();const audit:any[]=[];const svc=new AccountOperationService(repo,{append:async e=>{audit.push(e);}});await expect(svc.createTask(ctx,{accountId:"a1",projectId:"other",clientOrganizationId:"c1",operationKind:"QUERY",operatorUserId:"op"})).rejects.toThrow(/not assigned/);expect(audit[0].outcome).toBe("DENIED");});});
