import type {DatabasePort,Queryable} from "../../persistence/database-port.js";
import type {DemandEvidence,KeywordDataset,KeywordDecisionRecord,KeywordImportBatch,KeywordRecord,KeywordReviewPackage,KeywordScope,KeywordSource} from "./contracts.js";
import type {GenericKeywordRepository} from "./ports.js";

export class PgGenericKeywordRepository implements GenericKeywordRepository {
  constructor(private readonly db:DatabasePort){}
  async addDataset(v:KeywordDataset){await this.db.query(`INSERT INTO keyword_dataset(id,client_organization_id,project_id,name,source_kind,status,created_by_user_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[v.id,v.clientOrganizationId,v.projectId,v.name,v.source,v.status,v.createdByUserId,v.createdAt]);}
  async getDataset(s:KeywordScope,id:string){const r=await this.db.query<DatasetRow>(`SELECT * FROM keyword_dataset WHERE id=$1 AND client_organization_id=$2 AND project_id=$3`,[id,s.clientOrganizationId,s.projectId]);return r.rows[0]?dataset(r.rows[0]):undefined;}
  async addImportBatch(v:KeywordImportBatch){await this.db.query(`INSERT INTO keyword_import_batch(id,client_organization_id,project_id,dataset_id,source_kind,source_format,source_file_name,manifest_hash,status,accepted_count,rejected_count,imported_by_user_id,imported_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[v.id,v.clientOrganizationId,v.projectId,v.datasetId,v.source,v.format,v.fileName,v.manifestHash,v.status,v.acceptedCount,v.rejectedCount,v.importedByUserId,v.importedAt]);}
  async saveImportedBatch(batch:KeywordImportBatch,records:readonly KeywordRecord[],evidence:readonly DemandEvidence[]){await this.db.transaction(async tx=>{await insertBatch(tx,batch);for(const v of records)await insertRecord(tx,v);for(const v of evidence)await insertEvidence(tx,v);});}
  async addRecords(values:readonly KeywordRecord[]){await this.db.transaction(async tx=>{for(const v of values)await insertRecord(tx,v);});}
  async addDemandEvidence(values:readonly DemandEvidence[]){await this.db.transaction(async tx=>{for(const v of values)await insertEvidence(tx,v);});}
  async listRecords(s:KeywordScope,datasetId:string){const r=await this.db.query<RecordRow>(`SELECT * FROM keyword_record WHERE dataset_id=$1 AND client_organization_id=$2 AND project_id=$3 ORDER BY created_at,id`,[datasetId,s.clientOrganizationId,s.projectId]);return r.rows.map(record);}
  async addReviewPackage(v:KeywordReviewPackage){await this.db.transaction(async tx=>{await tx.query(`INSERT INTO keyword_review_package_v2(id,client_organization_id,project_id,dataset_id,version,status,submitted_by_user_id,submitted_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[v.id,v.clientOrganizationId,v.projectId,v.datasetId,v.version,v.status,v.submittedByUserId,v.submittedAt]);for(let i=0;i<v.keywordRecordIds.length;i++)await tx.query(`INSERT INTO keyword_review_package_item_v2(client_organization_id,project_id,review_package_id,keyword_record_id,position) VALUES($1,$2,$3,$4,$5)`,[v.clientOrganizationId,v.projectId,v.id,v.keywordRecordIds[i]!,i]);});}
  async getReviewPackage(s:KeywordScope,id:string){const r=await this.db.query<PackageRow>(`SELECT * FROM keyword_review_package_v2 WHERE id=$1 AND client_organization_id=$2 AND project_id=$3`,[id,s.clientOrganizationId,s.projectId]);if(!r.rows[0])return undefined;const items=await this.db.query<{keyword_record_id:string}>(`SELECT keyword_record_id FROM keyword_review_package_item_v2 WHERE review_package_id=$1 ORDER BY position`,[id]);const v=r.rows[0];return{id:v.id,clientOrganizationId:v.client_organization_id,projectId:v.project_id,datasetId:v.dataset_id,version:v.version,status:v.status,submittedByUserId:v.submitted_by_user_id,submittedAt:v.submitted_at.toISOString(),keywordRecordIds:items.rows.map(x=>x.keyword_record_id)};}
  async addDecision(v:KeywordDecisionRecord){await this.db.query(`INSERT INTO keyword_decision_v2(id,client_organization_id,project_id,review_package_id,keyword_record_id,decision,reviewer_user_id,note,decided_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[v.id,v.clientOrganizationId,v.projectId,v.reviewPackageId,v.keywordRecordId,v.decision,v.reviewerUserId,v.note??null,v.decidedAt]);}
}
interface DatasetRow{id:string;client_organization_id:string;project_id:string;name:string;source_kind:KeywordSource;status:"ACTIVE"|"ARCHIVED";created_by_user_id:string;created_at:Date}
interface RecordRow{id:string;client_organization_id:string;project_id:string;dataset_id:string;import_batch_id:string|null;keyword:string;normalized_keyword:string;source_kind:KeywordSource;category:string|null;note:string|null;region:string|null;period_start:Date|null;period_end:Date|null;created_by_user_id:string;created_at:Date}
interface PackageRow{id:string;client_organization_id:string;project_id:string;dataset_id:string;version:number;status:"OPEN"|"COMPLETED";submitted_by_user_id:string;submitted_at:Date}
const day=(v:Date|string|null)=>typeof v==="string"?v:v?.toISOString().slice(0,10);
function dataset(v:DatasetRow):KeywordDataset{return{id:v.id,clientOrganizationId:v.client_organization_id,projectId:v.project_id,name:v.name,source:v.source_kind,status:v.status,createdByUserId:v.created_by_user_id,createdAt:v.created_at.toISOString()};}
function record(v:RecordRow):KeywordRecord{return{id:v.id,clientOrganizationId:v.client_organization_id,projectId:v.project_id,datasetId:v.dataset_id,...(v.import_batch_id?{importBatchId:v.import_batch_id}:{}),keyword:v.keyword,normalizedKeyword:v.normalized_keyword,source:v.source_kind,...(v.category?{category:v.category}:{}),...(v.note?{note:v.note}:{}),...(v.region?{region:v.region}:{}),...(day(v.period_start)?{periodStart:day(v.period_start)}:{}),...(day(v.period_end)?{periodEnd:day(v.period_end)}:{}),createdByUserId:v.created_by_user_id,createdAt:v.created_at.toISOString()};}
async function insertRecord(db:Queryable,v:KeywordRecord){await db.query(`INSERT INTO keyword_record(id,client_organization_id,project_id,dataset_id,import_batch_id,keyword,normalized_keyword,source_kind,category,note,region,period_start,period_end,created_by_user_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[v.id,v.clientOrganizationId,v.projectId,v.datasetId,v.importBatchId??null,v.keyword,v.normalizedKeyword,v.source,v.category??null,v.note??null,v.region??null,v.periodStart??null,v.periodEnd??null,v.createdByUserId,v.createdAt]);}
async function insertBatch(db:Queryable,v:KeywordImportBatch){await db.query(`INSERT INTO keyword_import_batch(id,client_organization_id,project_id,dataset_id,source_kind,source_format,source_file_name,manifest_hash,status,accepted_count,rejected_count,imported_by_user_id,imported_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[v.id,v.clientOrganizationId,v.projectId,v.datasetId,v.source,v.format,v.fileName,v.manifestHash,v.status,v.acceptedCount,v.rejectedCount,v.importedByUserId,v.importedAt]);}
async function insertEvidence(db:Queryable,v:DemandEvidence){await db.query(`INSERT INTO demand_evidence(id,client_organization_id,project_id,keyword_record_id,source_kind,metric_kind,metric_value,metric_unit,region,period_start,period_end,source_reference,observed_at,recorded_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[v.id,v.clientOrganizationId,v.projectId,v.keywordRecordId,v.source,v.metricKind,v.metricValue,v.metricUnit??null,v.region??null,v.periodStart??null,v.periodEnd??null,v.sourceReference,v.observedAt,v.recordedAt]);}
