import type {Queryable} from "../../persistence/database-port.js";
import type {KeywordDatasetStatus,KeywordSource,KeywordScope} from "./contracts.js";
import {readLegacyBaiduAsGeneric} from "./legacy-baidu-adapter.js";

export interface GenericKeywordReadFilters {readonly datasetId?:string;readonly source?:KeywordSource;readonly batchId?:string;readonly status?:KeywordDatasetStatus}
export async function readGenericKeywordWorkspace(db:Queryable,scope:KeywordScope,filters:GenericKeywordReadFilters={}){
  const params:any[]=[scope.clientOrganizationId,scope.projectId],where=[`client_organization_id=$1`,`project_id=$2`];
  if(filters.datasetId){params.push(filters.datasetId);where.push(`id=$${params.length}`)}
  if(filters.source){params.push(filters.source);where.push(`source_kind=$${params.length}`)}if(filters.status){params.push(filters.status);where.push(`status=$${params.length}`)}
  const datasets=await db.query<any>(`SELECT id,name,source_kind,status,created_at FROM keyword_dataset WHERE ${where.join(" AND ")} ORDER BY created_at,id`,params as any);
  const ids=datasets.rows.map(x=>x.id);let imports:any[]=[];let records:any[]=[];let evidence:any[]=[];let packages:any[]=[];let decisions:any[]=[];
  if(ids.length){const batchParams:any[]=[scope.clientOrganizationId,scope.projectId,ids];let batchClause="";if(filters.batchId){batchParams.push(filters.batchId);batchClause=` AND id=$${batchParams.length}`;}imports=(await db.query<any>(`SELECT id,dataset_id,source_kind,source_format,source_file_name,status,accepted_count,rejected_count,imported_at FROM keyword_import_batch WHERE client_organization_id=$1 AND project_id=$2 AND dataset_id=ANY($3::uuid[])${batchClause} ORDER BY imported_at,id`,batchParams as any)).rows;
    const recordParams:any[]=[scope.clientOrganizationId,scope.projectId,ids];let recordClause="";if(filters.batchId){recordParams.push(filters.batchId);recordClause=` AND import_batch_id=$${recordParams.length}`;}records=(await db.query<any>(`SELECT id,dataset_id,import_batch_id,keyword,normalized_keyword,source_kind,category,note,region,period_start,period_end,created_at FROM keyword_record WHERE client_organization_id=$1 AND project_id=$2 AND dataset_id=ANY($3::uuid[])${recordClause} ORDER BY created_at,id`,recordParams as any)).rows;
    const recordIds=records.map(x=>x.id);if(recordIds.length)evidence=(await db.query<any>(`SELECT id,keyword_record_id,source_kind,metric_kind,metric_value::text,metric_unit,region,period_start,period_end,source_reference,observed_at,recorded_at FROM demand_evidence WHERE client_organization_id=$1 AND project_id=$2 AND keyword_record_id=ANY($3::uuid[]) ORDER BY observed_at,id`,[scope.clientOrganizationId,scope.projectId,recordIds] as any)).rows;
    packages=(await db.query<any>(`SELECT p.id,p.dataset_id,p.version,p.status,p.submitted_at,coalesce(json_agg(i.keyword_record_id ORDER BY i.position) FILTER(WHERE i.keyword_record_id IS NOT NULL),'[]') items FROM keyword_review_package_v2 p LEFT JOIN keyword_review_package_item_v2 i ON i.review_package_id=p.id WHERE p.client_organization_id=$1 AND p.project_id=$2 AND p.dataset_id=ANY($3::uuid[]) GROUP BY p.id ORDER BY p.submitted_at,p.id`,[scope.clientOrganizationId,scope.projectId,ids] as any)).rows;
    const packageIds=packages.map(x=>x.id);if(packageIds.length)decisions=(await db.query<any>(`SELECT id,review_package_id,keyword_record_id,decision,note,decided_at FROM keyword_decision_v2 WHERE client_organization_id=$1 AND project_id=$2 AND review_package_id=ANY($3::uuid[]) ORDER BY decided_at,id`,[scope.clientOrganizationId,scope.projectId,packageIds] as any)).rows;
  }
  const includeLegacy=!filters.status&&(!filters.source||filters.source==="BAIDU_KEYWORD")&&(!filters.datasetId||filters.datasetId===`legacy-baidu:${scope.projectId}`);const legacy=includeLegacy?await readLegacyBaiduAsGeneric(db,scope):{dataset:null,records:[],evidence:[]};const legacyRecords=filters.batchId?legacy.records.filter(x=>x.importBatchId===filters.batchId):legacy.records;
  const nextVersion=(datasetId:string)=>Math.max(0,...packages.filter(x=>x.dataset_id===datasetId).map(x=>Number(x.version)))+1;
  return{datasets:[...datasets.rows.map(x=>({id:x.id,name:x.name,source:x.source_kind,status:x.status,createdAt:x.created_at.toISOString(),nextReviewPackageVersion:nextVersion(x.id)})),...(legacy.dataset?[{id:legacy.dataset.id,name:legacy.dataset.name,source:legacy.dataset.source,status:legacy.dataset.status,createdAt:legacy.dataset.createdAt,readOnly:true,nextReviewPackageVersion:null}]:[])],imports:imports.map(x=>({id:x.id,datasetId:x.dataset_id,source:x.source_kind,format:x.source_format,fileName:x.source_file_name,status:x.status,acceptedCount:x.accepted_count,rejectedCount:x.rejected_count,importedAt:x.imported_at.toISOString()})),records:[...records.map(x=>({id:x.id,datasetId:x.dataset_id,importBatchId:x.import_batch_id??undefined,keyword:x.keyword,normalizedKeyword:x.normalized_keyword,source:x.source_kind,category:x.category??undefined,note:x.note??undefined,region:x.region??undefined,periodStart:date(x.period_start),periodEnd:date(x.period_end),createdAt:x.created_at.toISOString()})),...legacyRecords],evidence:[...evidence.map(x=>({id:x.id,keywordRecordId:x.keyword_record_id,source:x.source_kind,metricKind:x.metric_kind,metricValue:Number(x.metric_value),metricUnit:x.metric_unit??undefined,region:x.region??undefined,periodStart:date(x.period_start),periodEnd:date(x.period_end),sourceReference:x.source_reference,observedAt:x.observed_at.toISOString(),recordedAt:x.recorded_at.toISOString()})),...legacy.evidence.filter(x=>legacyRecords.some(r=>r.id===x.keywordRecordId))],reviewPackages:packages.map(x=>({id:x.id,datasetId:x.dataset_id,version:x.version,status:x.status,keywordRecordIds:x.items,submittedAt:x.submitted_at.toISOString()})),decisions:decisions.map(x=>({id:x.id,reviewPackageId:x.review_package_id,keywordRecordId:x.keyword_record_id,decision:x.decision,note:x.note??undefined,decidedAt:x.decided_at.toISOString()})),capabilities:{createDataset:true,manualAdd:true,genericCsvXlsxImport:true,humanReview:true,archive:true,legacyBaiduReadOnly:true}};
}
const date=(v:Date|string|null)=>v?(typeof v==="string"?v:v.toISOString().slice(0,10)):undefined;
