"use client";
import { useAsyncData } from "../runtime/index.js";
import { getAccountCenter } from "../../lib/api-client/domestic.js";
import type { AccountCenterReadModel } from "../../runtime/read-models/domestic-workspaces.js";
import { accountHealthLabel, accountStatusLabel, credentialStatusLabel, operationModeLabel, ownershipLabel } from "../account-keyword-runtime/labels.js";
import { OpsAsyncView } from "./OpsAsyncView.js";
import { opsPageStyles } from "./OpsPage.js";

const platformNames:Readonly<Record<string,string>>={DOUBAO:"豆包",QWEN:"通义千问",DEEPSEEK:"DeepSeek",YUANBAO:"腾讯元宝",BAIJIAHAO:"百家号",TOUTIAO:"头条号",WECHAT_OFFICIAL:"微信公众号",ZHIHU:"知乎",XIAOHONGSHU:"小红书",SOHU:"搜狐号",NETEASE:"网易号",PENGUIN:"企鹅号",DOUYIN:"抖音",BILIBILI:"B站",CSDN:"CSDN",JIANSHU:"简书"};

export function OpsAccountReadPanel(){const {state,reload}=useAsyncData<AccountCenterReadModel>(()=>getAccountCenter(),{isEmpty:(model)=>model.accounts.length===0});return <section className={opsPageStyles.panel}><div className="section-heading"><div><h2>账号总览</h2><p>只展示账号业务状态，不显示凭证引用或内部标识。</p></div><button type="button" className="button button-secondary" onClick={reload}>刷新</button></div><OpsAsyncView state={state} empty={<p className={opsPageStyles.muted}>尚未登记账号。</p>}>{(model)=><><div className={opsPageStyles.grid}><div className={opsPageStyles.card}><p className={opsPageStyles.value}>{model.totals.all}</p><p className={opsPageStyles.label}>账号总数</p></div><div className={opsPageStyles.card}><p className={opsPageStyles.value}>{model.totals.platformOwned}</p><p className={opsPageStyles.label}>平台自有</p></div><div className={opsPageStyles.card}><p className={opsPageStyles.value}>{model.totals.needsAttention}</p><p className={opsPageStyles.label}>需要关注</p></div><div className={opsPageStyles.card}><p className={opsPageStyles.value}>{model.totals.pendingTasks}</p><p className={opsPageStyles.label}>待处理任务</p></div></div><div className={opsPageStyles.tableWrap}><table className={opsPageStyles.table}><thead><tr><th>平台</th><th>账号名称</th><th>归属</th><th>账号状态</th><th>凭证状态</th><th>账号健康</th><th>操作方式</th></tr></thead><tbody>{model.accounts.map((item)=><tr key={item.id}><td>{platformNames[item.platformCode]??"国内平台"}</td><td>{item.displayLabel}</td><td>{ownershipLabel[item.ownership]}</td><td>{accountStatusLabel[item.status]}</td><td>{item.credentialConfigured?credentialStatusLabel[item.credentialStatus]:"待配置"}</td><td>{accountHealthLabel[item.healthStatus]}</td><td>{operationModeLabel[item.operationMode]}</td></tr>)}</tbody></table></div></>}</OpsAsyncView></section>}
