"use client";
import {useRouter} from "next/navigation";
import {type FormEvent,useState} from "react";
import type {AgencyWorkflowStage,AgencyWorkflowStatus} from "../../runtime/agency-delivery/contracts.js";
import {ApiClientError} from "../../lib/api-client/index.js";
import {chineseApiError} from "../../runtime/ui-adapters/chinese-errors.js";
import {submitDeliveryAction,submitWorkflowTransition,type AgencyDeliveryScope} from "./actions.js";

const STAGES:readonly {value:AgencyWorkflowStage;label:string}[]=[{value:"CLIENT_PROFILE",label:"客户资料"},{value:"PROJECT_PROFILE",label:"项目资料"},{value:"ENTERPRISE_KNOWLEDGE",label:"企业知识"},{value:"ACCOUNT_AUTHORIZATION",label:"账号授权"},{value:"BAIDU_KEYWORDS",label:"百度关键词"},{value:"AI_EXPANSION",label:"AI 拓词"},{value:"USER_QUESTION_CONFIRMATION",label:"用户问题确认"},{value:"CONTENT_TASK",label:"内容任务"},{value:"CONTENT_REVIEW",label:"内容审核"},{value:"CHINA_AI_PROBE",label:"国内 AI 查询"},{value:"REPORT",label:"报告"},{value:"DELIVERY",label:"交付"},{value:"RETROSPECTIVE",label:"复盘"}];
const STATUSES:readonly {value:AgencyWorkflowStatus;label:string}[]=[{value:"NOT_STARTED",label:"未开始"},{value:"IN_PROGRESS",label:"进行中"},{value:"WAITING_CLIENT",label:"等待客户"},{value:"BLOCKED",label:"已阻塞"},{value:"COMPLETED",label:"已完成"}];
type Feedback={kind:"idle"|"loading"|"success"|"error";message:string};
export interface AgencyDeliveryActionsProps extends AgencyDeliveryScope{readonly currentStage?:AgencyWorkflowStage;readonly canMarkReady?:boolean;readonly canRegisterDelivered?:boolean}

export function AgencyDeliveryActions({currentStage="CLIENT_PROFILE",canMarkReady=false,canRegisterDelivered=false,...scope}:AgencyDeliveryActionsProps){const router=useRouter();const[feedback,setFeedback]=useState<Feedback>({kind:"idle",message:""});const[deliveryAction,setDeliveryAction]=useState<"MARK_READY"|"REGISTER_DELIVERED">(canMarkReady?"MARK_READY":"REGISTER_DELIVERED");const busy=feedback.kind==="loading";
  async function run(action:()=>Promise<any>,success:string){setFeedback({kind:"loading",message:"正在保存…"});try{const result=await action();if(!result.ok){setFeedback({kind:"error",message:chineseApiError(result.code,result.message)});return}setFeedback({kind:"success",message:success});router.refresh()}catch(error){setFeedback({kind:"error",message:error instanceof ApiClientError&&error.kind==="NETWORK"?"无法连接本地服务，请稍后重试。":"操作失败，请稍后重试。"})}}
  function workflow(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);void run(()=>submitWorkflowTransition(scope,{stage:String(data.get("stage")) as AgencyWorkflowStage,toStatus:String(data.get("status")) as AgencyWorkflowStatus,reason:String(data.get("reason")??"").trim()}),"业务阶段已更新。")}function delivery(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const action=String(data.get("action")) as "MARK_READY"|"REGISTER_DELIVERED";const receiptReference=String(data.get("receiptReference")??"").trim();void run(()=>submitDeliveryAction(scope,{action,...(receiptReference?{receiptReference}:{})}),action==="MARK_READY"?"项目已标记为待交付。":"人工交付已登记。")}return <section className="cp-card" aria-labelledby="agency-delivery-actions"><div className="cp-section-header"><div><h2 id="agency-delivery-actions">推进项目与交付</h2><p>所有操作均写入真实业务记录，系统不会自动发布。</p></div></div><form className="cp-form-grid" onSubmit={workflow}><label>业务阶段<select name="stage" defaultValue={currentStage} disabled={busy}>{STAGES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>更新为<select name="status" defaultValue="IN_PROGRESS" disabled={busy}>{STATUSES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label className="cp-field-wide">操作说明<input name="reason" required minLength={2} placeholder="请填写本次推进原因" disabled={busy}/></label><button className="cp-button cp-button-primary" type="submit" disabled={busy}>保存阶段</button></form>{canMarkReady||canRegisterDelivered?<form className="cp-form-grid" onSubmit={delivery}><label>交付动作<select name="action" value={deliveryAction} onChange={event=>setDeliveryAction(event.target.value as typeof deliveryAction)} disabled={busy}>{canMarkReady?<option value="MARK_READY">标记为待交付</option>:null}{canRegisterDelivered?<option value="REGISTER_DELIVERED">登记人工交付</option>:null}</select></label><label>交付回执编号<input name="receiptReference" required={deliveryAction==="REGISTER_DELIVERED"} placeholder={deliveryAction==="REGISTER_DELIVERED"?"请输入人工交付回执编号":"本操作无需填写"} disabled={busy||deliveryAction!=="REGISTER_DELIVERED"}/></label><button className="cp-button cp-button-primary" type="submit" disabled={busy}>确认交付动作</button></form>:<p className="cp-empty-state">当前项目尚未达到可交付状态。</p>}{feedback.message?<p className={feedback.kind==="error"?"cp-feedback cp-feedback-error":"cp-feedback cp-feedback-success"} role={feedback.kind==="error"?"alert":"status"}>{feedback.message}</p>:null}</section>}
