"use client";
import { useAsyncData } from "@/components/runtime";
import { AgencyAsyncView, getAgencyClients } from "@/components/agency-runtime";
import { AccountRegistrationPanel, accountHealthLabel, accountRiskLabel, accountStatusLabel, authorizationStatusLabel, credentialStatusLabel, ownershipLabel } from "@/components/account-keyword-runtime";
import { getAccountCenter } from "@/lib/api-client/domestic";
import type { AccountCenterReadModel } from "@/runtime/read-models/domestic-workspaces";
import { ACCOUNT_PLATFORM_REGISTRY } from "@/runtime/accounts/platform-registry";
import type { Result } from "@/lib/api-client";

interface View { readonly agencyOrganizationId: string; readonly accounts: AccountCenterReadModel }
async function load(): Promise<Result<View>> { const agency=await getAgencyClients(); if(!agency.ok)return agency; const accounts=await getAccountCenter(); if(!accounts.ok)return accounts; return {ok:true,data:{agencyOrganizationId:agency.data.agencyOrganizationId,accounts:accounts.data}}; }
const platforms=ACCOUNT_PLATFORM_REGISTRY.map((item)=>({code:item.code,label:item.displayName,type:item.accountType}));
const needsAttention=(account:AccountCenterReadModel["accounts"][number])=>account.riskStatus==="ATTENTION"||account.riskStatus==="BLOCKED"||account.credentialStatus==="EXPIRED"||account.credentialStatus==="REVOKED";

export default function Page(){const {state,reload}=useAsyncData<View>(load);return <><header className="cp-page-header"><div><p className="eyebrow">代理商工作台</p><h1>账号中心</h1><span>查看当前代理商及已授权客户范围内的账号；敏感凭据不会在页面显示。</span></div></header>
  <AgencyAsyncView state={state}>{({agencyOrganizationId,accounts})=><div className="cp-stack"><section className="cp-section"><h2>账号概览</h2><p>账号 {accounts.totals.all} 个 · 需要关注 {accounts.totals.needsAttention} 个 · 待处理任务 {accounts.totals.pendingTasks} 项</p>
    {accounts.accounts.length===0?<div className="cp-empty-state"><h3>当前授权范围内没有账号</h3><p>尚未登记代理商账号，且当前客户范围没有可查看的客户账号。登记代理商自有账号后，可继续完成授权与项目分配。</p><a className="cp-button cp-button-primary" href="#agency-account-register">登记账号</a></div>:<div className="cp-table-wrap"><table className="cp-data-table"><thead><tr><th>账号</th><th>归属</th><th>账号状态</th><th>凭据状态</th><th>授权</th><th>健康与风险</th><th>最近检查</th><th>授权项目</th></tr></thead><tbody>{accounts.accounts.map((account)=><tr key={account.id}><td>{account.displayLabel}</td><td>{ownershipLabel[account.ownership]}</td><td>{accountStatusLabel[account.status]}</td><td>{credentialStatusLabel[account.credentialStatus]}</td><td>{account.authorizationStatus===null?"尚未授权":authorizationStatusLabel[account.authorizationStatus]}</td><td>{accountHealthLabel[account.healthStatus]} / {accountRiskLabel[account.riskStatus]}{account.lastException?<><br/>最近异常：{account.lastException}</>:null}</td><td>{account.lastCheckedAt?new Date(account.lastCheckedAt).toLocaleString("zh-CN"):"尚未检查"}</td><td>{account.authorizedProjects.length?account.authorizedProjects.map((project)=><div key={project.id}>{project.name}</div>):"尚未授权项目"}</td></tr>)}</tbody></table></div>}
  </section><section className="cp-section" id="attention"><h2>异常账号</h2>{accounts.accounts.filter(needsAttention).length===0?<p className="cp-empty-state">当前授权范围内没有异常账号。</p>:<ul className="cp-list">{accounts.accounts.filter(needsAttention).map(account=><li className="cp-list-row" key={account.id}><span className="cp-list-title">{account.displayLabel}</span><span className="cp-list-meta">{credentialStatusLabel[account.credentialStatus]} · {accountHealthLabel[account.healthStatus]} · {accountRiskLabel[account.riskStatus]}</span></li>)}</ul>}</section><section className="cp-section" id="agency-account-register"><h2>登记代理商自有账号</h2><AccountRegistrationPanel platforms={platforms} ownership="AGENCY_OWNED" agencyOrganizationId={agencyOrganizationId} onRegistered={reload}/></section></div>}</AgencyAsyncView></>}
