import { recordAuditEvent } from "../../contracts/tenancy/audit.js";
import type { Queryable } from "../../persistence/database-port.js";
import type { AccountAuditEntry, AccountAuditWriter } from "./authorization-service.js";
import type { AccountAssignment, AccountAuthorization, AccountHealth, AccountOperationResult, AccountOperationTask, AccountUsageRecord, PlatformAccount } from "./entities.js";
import type { AccountRepository } from "./ports.js";

const iso=(v:Date|string|null):string|null=>v===null?null:(v instanceof Date?v.toISOString():v);
const account=(r:any):PlatformAccount=>({id:r.id,platformCode:r.platform_code,accountType:r.account_type,ownership:r.ownership,agencyOrganizationId:r.agency_organization_id,clientOrganizationId:r.client_organization_id,displayLabel:r.display_label,secretReference:r.secret_reference,credentialStatus:r.credential_status,lastVerifiedAt:iso(r.last_verified_at),status:r.status,operationMode:r.operation_mode,createdByUserId:r.created_by_user_id,createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!});
const authorization=(r:any):AccountAuthorization=>({id:r.id,accountId:r.account_id,clientOrganizationId:r.client_organization_id,agencyOrganizationId:r.agency_organization_id,status:r.status,authorizedByUserId:r.authorized_by_user_id,authorizedAt:iso(r.authorized_at),revokedByUserId:r.revoked_by_user_id,revokedAt:iso(r.revoked_at),createdAt:iso(r.created_at)!});
const assignment=(r:any):AccountAssignment=>({id:r.id,accountId:r.account_id,projectId:r.project_id,clientOrganizationId:r.client_organization_id,operatorUserId:r.operator_user_id,status:r.status,assignedByUserId:r.assigned_by_user_id,assignedAt:iso(r.assigned_at)!,revokedAt:iso(r.revoked_at)});
const task=(r:any):AccountOperationTask=>({id:r.id,accountId:r.account_id,assignmentId:r.assignment_id,projectId:r.project_id,clientOrganizationId:r.client_organization_id,operationKind:r.operation_kind,operationMode:r.operation_mode,status:r.status,requestedByUserId:r.requested_by_user_id,operatorUserId:r.operator_user_id,requestedAt:iso(r.requested_at)!,startedAt:iso(r.started_at),completedAt:iso(r.completed_at)});

export class PgAccountRepository implements AccountRepository {
  constructor(private readonly db:Queryable){}
  async createAccount(i:Omit<PlatformAccount,"id"|"createdAt"|"updatedAt">){const q=await this.db.query<any>(`INSERT INTO platform_account (platform_code,account_type,ownership,agency_organization_id,client_organization_id,display_label,secret_reference,credential_status,last_verified_at,status,operation_mode,created_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[i.platformCode,i.accountType,i.ownership,i.agencyOrganizationId,i.clientOrganizationId,i.displayLabel,i.secretReference,i.credentialStatus,i.lastVerifiedAt,i.status,i.operationMode,i.createdByUserId]);return account(q.rows[0]);}
  async findAccountById(id:string){const q=await this.db.query<any>("SELECT * FROM platform_account WHERE id=$1",[id]);return q.rows[0]?account(q.rows[0]):null;}
  async addAuthorization(i:Omit<AccountAuthorization,"id"|"createdAt">){const q=await this.db.query<any>(`INSERT INTO account_authorization (account_id,client_organization_id,agency_organization_id,status,authorized_by_user_id,authorized_at,revoked_by_user_id,revoked_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[i.accountId,i.clientOrganizationId,i.agencyOrganizationId,i.status,i.authorizedByUserId,i.authorizedAt,i.revokedByUserId,i.revokedAt]);return authorization(q.rows[0]);}
  async findActiveAuthorization(id:string){const q=await this.db.query<any>("SELECT * FROM account_authorization WHERE account_id=$1 AND status='AUTHORIZED'",[id]);return q.rows[0]?authorization(q.rows[0]):null;}
  async revokeAuthorization(id:string,user:string,at:string){const q=await this.db.query<any>("UPDATE account_authorization SET status='REVOKED',revoked_by_user_id=$2,revoked_at=$3 WHERE id=$1 AND status='AUTHORIZED' RETURNING *",[id,user,at]);if(!q.rows[0])throw new Error("Active authorization not found");return authorization(q.rows[0]);}
  async addAssignment(i:Omit<AccountAssignment,"id"|"assignedAt"|"revokedAt">){const q=await this.db.query<any>(`INSERT INTO account_assignment (account_id,project_id,client_organization_id,operator_user_id,status,assigned_by_user_id) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`,[i.accountId,i.projectId,i.clientOrganizationId,i.operatorUserId,i.status,i.assignedByUserId]);return assignment(q.rows[0]);}
  async findActiveAssignment(a:string,p:string){const q=await this.db.query<any>("SELECT * FROM account_assignment WHERE account_id=$1 AND project_id=$2 AND status='ACTIVE'",[a,p]);return q.rows[0]?assignment(q.rows[0]):null;}
  async addHealth(i:Omit<AccountHealth,"id">){const q=await this.db.query<any>(`INSERT INTO account_health (account_id,health_status,risk_status,daily_usage_count,failure_count,last_exception,last_executed_at,checked_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[i.accountId,i.healthStatus,i.riskStatus,i.dailyUsageCount,i.failureCount,i.lastException,i.lastExecutedAt,i.checkedAt]);const r=q.rows[0];return{id:r.id,...i};}
  async addUsage(i:Omit<AccountUsageRecord,"id">){const q=await this.db.query<any>(`INSERT INTO account_usage_record (account_id,project_id,client_organization_id,operator_user_id,operation_kind,succeeded,failure_category,occurred_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[i.accountId,i.projectId,i.clientOrganizationId,i.operatorUserId,i.operationKind,i.succeeded,i.failureCategory,i.occurredAt]);return{id:q.rows[0].id,...i};}
  async createOperationTask(i:Omit<AccountOperationTask,"id"|"requestedAt"|"startedAt"|"completedAt">){const q=await this.db.query<any>(`INSERT INTO account_operation_task (account_id,assignment_id,project_id,client_organization_id,operation_kind,operation_mode,status,requested_by_user_id,operator_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[i.accountId,i.assignmentId,i.projectId,i.clientOrganizationId,i.operationKind,i.operationMode,i.status,i.requestedByUserId,i.operatorUserId]);return task(q.rows[0]);}
  async completeOperationTask(id:string,status:"SUCCEEDED"|"FAILED",at:string){const q=await this.db.query<any>("UPDATE account_operation_task SET status=$2,completed_at=$3 WHERE id=$1 AND status IN ('PENDING','IN_PROGRESS') RETURNING *",[id,status,at]);if(!q.rows[0])throw new Error("Open task not found");return task(q.rows[0]);}
  async findOperationTaskById(id:string){const q=await this.db.query<any>("SELECT * FROM account_operation_task WHERE id=$1",[id]);return q.rows[0]?task(q.rows[0]):null;}
  async addOperationResult(i:Omit<AccountOperationResult,"id"|"recordedAt">){const q=await this.db.query<any>(`INSERT INTO account_operation_result (task_id,account_id,status,result_summary,failure_category,publication_receipt_id,recorded_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id,recorded_at`,[i.taskId,i.accountId,i.status,i.resultSummary,i.failureCategory,i.publicationReceiptId,i.recordedByUserId]);return{id:q.rows[0].id,...i,recordedAt:iso(q.rows[0].recorded_at)!};}
}

export class PgAccountAuditWriter implements AccountAuditWriter {
  constructor(private readonly db:Queryable){}
  async append(e:AccountAuditEntry){const at=new Date();const event=recordAuditEvent({organizationId:e.actorOrganizationId,actorUserId:e.actorUserId,actorOrganizationId:e.actorOrganizationId,clientOrganizationId:e.clientOrganizationId,projectId:e.projectId,action:e.action,targetType:e.targetType,targetId:e.targetId,metadata:{...(e.metadata??{}),outcome:e.outcome},now:at});await this.db.query(`INSERT INTO audit_event (organization_id,actor_user_id,actor_organization_id,client_organization_id,project_id,action,target_type,target_id,metadata,event_hash,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[event.organizationId,event.actorUserId,event.actorOrganizationId,event.clientOrganizationId,event.projectId,event.action,event.targetType,event.targetId,JSON.stringify(event.metadata),event.eventHash,event.createdAt]);}
}
